export const SET_GNOMES = 'SET_GNOMES';
export const FETCH_GNOMES_FAILED = 'FETCH_GNOMES_FAILED';
export const SET_INITIALIZED = 'SET_INITIALIZED';
export const SET_GNOMES_FILTER = 'SET_GNOMES_FILTER';
export const SET_GNOME_SELECTED = 'SET_GNOME_SELECTED';


